#!/usr/bin/env php
<?php

declare(strict_types=1);

use Symfony\Component\Console\Input\ArgvInput;

require __DIR__.'/vendor/autoload.php';

$app = require __DIR__.'/bootstrap.php';

exit($app->handleCommand(new ArgvInput));
